### PR TITLE
token response follows OAuth2 spec

### LINKED ISSUE #80: Apigee OAuth response does not conform to OAuth 2 spec
Issues filed on Github are not subject to service level agreements (SLAs) and responses should be
assumed to be on an ad-hoc volunteer basis. The [Apigee community board](https://community.apigee.com/) 
is recommended as for community support and is regularly checked by Apigee experts.

Apigee customers should use [formal support channels](https://cloud.google.com/apigee/support).

---
**Describe the issue**
The OAuth token response does not conform to the RFC [here](https://tools.ietf.org/html/rfc6749)

**Additional context**
I have made the changes here: https://github.com/srinandan/apigee-remote-service-cli/blob/master/proxies/remote-proxy-gcp/apiproxy/resources/jsc/set-response.js

### PR DESCRIPTION
**Pull request by rockspore**
fix #80

### CODE REVIEW

**Comment by rockspore** [comment]
`token` is replaced by `access_token` in the endpoint response. The `token` cmd is updated accordingly.

**Comment by theganyo** [comment]
Changing `token` to `access_token` would seem to be a breaking change. Is there a reason?

**Comment by rockspore** [comment]
> Changing `token` to `access_token` would seem to be a breaking change. Is there a reason?

`token` is not part of the OAuth spec so I removed it. But it'd indeed be a breaking change. Let me add it back.

**Comment by rockspore** [comment]
`scope` needs a bit more investigation.

**Comment by rockspore** [comment]
> `scope` needs a bit more investigation.

The behavior of our `/token` endpoint is within the spec. All good.

**Review by theganyo — APPROVED** [review]

**Pull request merged**
