### PR TITLE
Set createNew to true in AssignMessage policies used for response

### LINKED ISSUE #33: AssignMessage Response createNew true
**Describe the issue**
AssignMessage policies which are used to send a response should set createNew="true". This will prevent request headers from being copied to the response. When request headers are copied to the response, it can interfere with http 2. The workaround was to turn off http 2 on the client (apigee-remote-service-envoy).

However, if createNew is set to true, then http 2 can be used by apigee-remote-service-envoy.

**Steps to Reproduce**
Run apigee-remote-service without setting `GODEBUG=http2client=0` you will notice errors like this:

stream error: stream ID 11; PROTOCOL_ERROR; mix of request and response pseudo headers

**Platform (include version)**
OS: 
Envoy: 
Kubernetes: 1.16
Istio: ASM 1.5.8

**Additional context**

### PR DESCRIPTION
**Pull request by rockspore**
Fix #33 

As my developing environment udpates golang automatically, the use of `string(int)` was changed to `string(rune(int))` to avoid error in go 1.15

### CODE REVIEW

**Comment by theganyo** [comment]
There are a number of places in -envoy and -cli repos that set GODEBUG. Can these now be removed?

**Comment by theganyo** [comment]
So, it sounds like this doesn't actually addresses the problem described in #33.

**Comment by rockspore** [comment]
The gcp-managed should now all work with an http2 client. The GODEBUG environment variable has been removed. The sample config in the -envoy repo needs such update as well.

Note: The version of go in go.mod is changed to 1.14.

**Comment by theganyo** [comment]
ok. please update the envoy sample. and let's update the other mod files as well.

**Pull request merged**
