### PR TITLE
output error

### LINKED ISSUE #62: CLI is exiting on `bindings verify ...` error but it does not print the error message out.
When an app for a bound product is not associated with the product, the proper output should be:
```
$./apigee-remote-service-cli bindings verify ...
Verifying
Verifying apps associated with product bound-prod-1:
  app app-1 associated with product bound-prod-1 is not associated with remote-service product
```
and it now outputs:
```
$./apigee-remote-service-cli bindings verify ...
Verifying
Verifying apps associated with product bound-prod-1:
```
because the last line of message was returned in an error, causing the process to exit with status 1, while the error itself is not  streamed to anywhere.

### PR DESCRIPTION
**Pull request by rockspore**
fix #62

### CODE REVIEW

**Comment by theganyo** [comment]
I'm not sure I understand this change. Why is it necessary to both print and return the error?

**Comment by rockspore** [comment]
> I'm not sure I understand this change. Why is it necessary to both print and return the error?

I updated the issue #62 to explain the problem. First of all, it's better if we print the error during the verifying process. It could break the order of the printed message if we print all errors in the end. For example, something below could happen:
```
Verifying
...
Verifying apps associated with product bound-prod-2:
Verifying apps associated with product bound-prod-1:
  app app-2 associated with product bound-prod-2 is not associated with remote-service product
  app app-1 associated with product bound-prod-1 is not associated with remote-service product
```

Meanwhile, the program is using the returned error to exit with status 1. It is indeed not necessary to return an error with the printed message. But some error should be returned.

**Comment by theganyo** [comment]
Ok, thanks. I guess my real question is more like: why doesn't the library print the returned error. BTW: Why wasn't this caught by the test? Could it be?

**Comment by rockspore** [comment]
> Ok, thanks. I guess my real question is more like: why doesn't the library print the returned error. BTW: Why wasn't this caught by the test? Could it be?

As we discussed before, it'd be tricky to do tests when the program is expected to exit with error status. Prior to exiting with status 1 on error, the tests were indeed checking and exact output. I had to remove the check to avoid test crash.

**Pull request merged**
